# Generated by Django 3.1.4 on 2020-12-29 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 12, 29, 14, 37, 37, 669056, tzinfo=utc))),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', markdownx.models.MarkdownxField()),
                ('background_image', models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/12/29')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
