# Generated by Django 3.1.4 on 2021-01-10 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201230_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(default='img/header.jpg', upload_to='backgrounds/2021/01/10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 7, 23, 6, 606557, tzinfo=utc)),
        ),
    ]
