# Generated by Django 3.1.4 on 2020-12-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pollschoice_pollsquestion_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollsChoice',
        ),
        migrations.DeleteModel(
            name='PollsQuestion',
        ),
    ]
