# Generated by Django 3.1.4 on 2020-12-29 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201229_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ImageField(default='img/header.jpg', upload_to='backgrounds/2020/12/29'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 7, 18, 2, 271638, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
