# Generated by Django 3.1.4 on 2020-12-29 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201229_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 7, 18, 32, 688265, tzinfo=utc)),
        ),
    ]
